apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/audif90/argocd-example-apps # Repo infra-mu
    targetRevision: HEAD
    path: rollout-manifests # Mengarah ke folder yang berisi rollout.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rollouts-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true