apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-canary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/audif90/argocd-example-apps
    targetRevision: HEAD
    path: helm-guestbook
    helm:
      values: |
        # 1. Mencegah bentrok nama dengan Deployment Prod!
        fullnameOverride: "helm-guestbook-canary"
        replicaCount: 1
        image:
          tag: "0.2"
        # 2. Resource Limits
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook # <-- Disatukan kembali ke namespace Production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true